keralazawaj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("web.urls", namespace="web")),
        path("api/user/", include("user.urls", namespace="user")),
        path("api-auth/", include("rest_framework.urls")),
        path("official/", include("official.urls", namespace="official")),
        path("official/api/", include("officialapi.urls", namespace="officialapi")),
        path("tinymce/", include("tinymce.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

admin.site.site_header = "Keralazawaj Administration"
admin.site.site_title = "Keralazawaj Admin Portal"
admin.site.index_title = "Welcome to Keralazawaj Admin Portal"

official/urls.py
from official import views

from django.urls import path


app_name = "official"


urlpatterns = [
    path("", views.admin_login, name="admin_login"),
    path("dashboard/", views.admin_dashboard, name="admin_dashboard"),
    path("pending-verifications/", views.pending_verification, name="pending_verification"),
    path("verified-user/", views.verified_user, name="verified_user"),
    path("males/", views.males, name="males"),
    path("females/", views.females, name="females"),
    path("succes-stories/", views.stories, name="stories"),
    path("testimonial/", views.testimonial, name="testimonial"),
    path("view-profile/<str:pk>/", views.view_profile, name="view-profile"),
    path("uncompleted-profile/", views.uncompleted_profiles, name="uncompleted_profiles"),
    path("subscription-plans/", views.subscription_plans, name="subscription_plans"),
]

web/urls.py
from . import views
from django.urls import path


app_name = "web"

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login, name="login"),
    path("register/<int:registerid>", views.register, name="register"),
    path("pic-upload/", views.profile_picupload, name="profile_picupload"),
    path("edit-profilepic/<str:id>/", views.edit_profilepic, name="edit_profilepic"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("like/", views.like, name="like"),
    path("like-premium/", views.likes_premium, name="likes_premium"),
    path("matches/", views.matches, name="matches"),
    path("matches-premium/", views.matches_premium, name="matches_premium"),
    path("view-profile/<str:pk>/", views.view_profile, name="view_profile"),
    path("view-profile-premium", views.view_profile_premium, name="view_profile_premium"),
    path("user-profile/", views.user_profile, name="user_profile"),
    path("contact/", views.contact, name="contact"),
    path("privacy/", views.privacy, name="privacy"),
    path("terms&condition/", views.terms, name="terms"),
    path("password_reset/", views.password_reset, name="password_reset"),
    path("chat/", views.chat, name="chat"),
    path("user-ajax", views.user_ajax, name="user_ajax"),
    path("chat-two/", views.chattwo, name="chat_two"),
    path("chat-direct/", views.chat_direct, name="chat_direct"),
    path("change_password/<str:email>/", views.change_password, name="change_password"),
    # --------------
    path("subscription-plans-view/", views.subscription_plans_view, name="subscription_plans_view"),
    path("payment-view/", views.payment_view, name="payment_view"),
]

templates/adminpage/partials/footer.html
{% load static %}

<footer class="footer">
    <div class="d-sm-flex justify-content-center">
      <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2021. All rights reserved.Passionately created by <a href="https://gedexo.com/" target="_blank" style="text-decoration: none;"> Gedexo</a> Designs</span>
      <!-- <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="ti-heart text-danger ml-1"></i></span> -->
    </div>
  </footer>

templates/adminpage/partials/header.html
{% load static %}
<nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
    <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
      <a class="navbar-brand brand-logo mr-5 bismi-title-ad" href="{% url 'official:admin_dashboard' %}">
        <!-- <img src="{% static 'web/images/KeralZawaj.svg' %}" class="mr-2 " alt="logo"/> -->
        Kerala Zawaj
         
      <a class="navbar-brand brand-logo-mini" href="{% url 'official:admin_dashboard' %}">
        <img src="{% static 'web/images/Kerala-icon.png' %}" alt="logo"/>
        
      </a>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
      <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
        <span class="icon-menu"></span>
      </button>
      <ul class="navbar-nav mr-lg-2">
        <!-- <li class="nav-item nav-search d-none d-lg-block">
          <div class="input-group">
            <div class="input-group-prepend hover-cursor" id="navbar-search-icon">
              <span class="input-group-text" id="search">
                <i class="icon-search"></i>
              </span>
            </div>
            <input type="text" class="form-control" id="navbar-search-input" placeholder="Search now" aria-label="search" aria-describedby="search">
          </div>
        </li> -->
      </ul>
      <ul class="navbar-nav navbar-nav-right">
        <!-- <li class="nav-item dropdown">
          <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-toggle="dropdown">
            <i class="icon-bell mx-0"></i>
            <span class="count"></span>
          </a>
          <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="notificationDropdown">
            <p class="mb-0 font-weight-normal float-left dropdown-header">Notifications</p>
            <a class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                <div class="preview-icon bg-success">
                  <i class="ti-info-alt mx-0"></i>
                </div>
              </div>
              <div class="preview-item-content">
                <h6 class="preview-subject font-weight-normal">Application Error</h6>
                <p class="font-weight-light small-text mb-0 text-muted">
                  Just now
                </p>
              </div>
            </a>
            <a class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                <div class="preview-icon bg-warning">
                  <i class="ti-settings mx-0"></i>
                </div>
              </div>
              <div class="preview-item-content">
                <h6 class="preview-subject font-weight-normal">Settings</h6>
                <p class="font-weight-light small-text mb-0 text-muted">
                  Private message
                </p>
              </div>
            </a>
            <a class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                <div class="preview-icon bg-info">
                  <i class="ti-user mx-0"></i>
                </div>
              </div>
              <div class="preview-item-content">
                <h6 class="preview-subject font-weight-normal">New user registration</h6>
                <p class="font-weight-light small-text mb-0 text-muted">
                  2 days ago
                </p>
              </div>
            </a>
          </div>
        </li> -->
        <li class="nav-item nav-profile dropdown">
          <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
            <img src="{% static 'adminpage/images/default.png' %}" alt="profile"/>
          </a>
          <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
            <a class="dropdown-item" href="{% url 'web:index' %}"> 
              <i class="ti-settings text-primary"></i>
              view site
            </a>
            <a id="logout" class="dropdown-item">
              <i class="ti-power-off text-primary"></i>
              Logout
            </a>
          </div>
        </li>
        
      </ul>
      <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
        <span class="icon-menu"></span>
      </button>
    </div>
  </nav>


templates/adminpage/partials/sidebar.html
{% load static %}
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'official:admin_dashboard' %}">
          <i class="icon-grid menu-icon"></i>
          <span class="menu-title">Dashboard</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'official:verified_user' %}" aria-expanded="false" aria-controls="form-elements">
          <!-- <i class="icon-columns menu-icon"></i> -->
          <i class="fas fa-user-check menu-icon"></i>
          <span class="menu-title">Registered Users</span>
          <!-- <i class="menu-arrow"></i> -->
        </a>
       
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'official:males' %}" aria-expanded="false" aria-controls="charts">
          <!-- <i class="icon-bar-graph menu-icon"></i> -->
          <i class="fas fa-male menu-icon"></i>

          <span class="menu-title">Males</span>
          <!-- <i class="menu-arrow"></i> -->
        </a>
       
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'official:females' %}" aria-expanded="false" aria-controls="tables">
          <!-- <i class="icon-grid-2 menu-icon"></i> -->
          <i class="fas fa-female menu-icon"></i>
          <span class="menu-title">Females</span>
          <!-- <i class="menu-arrow"></i> -->
        </a>
        
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'official:uncompleted_profiles' %}" aria-expanded="false" aria-controls="tables">
          <!-- <i class="icon-grid-2 menu-icon"></i> -->
          
          <i class="fas fa-clipboard-list  menu-icon"></i>
          <span class="menu-title">Incompleted Profile</span>
          <!-- <i class="menu-arrow"></i> -->
        </a>
        
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'official:subscription_plans' %}" aria-expanded="false" aria-controls="tables">
          <!-- <i class="icon-grid-2 menu-icon"></i> -->
          
          <i class="fas fa-clipboard-list  menu-icon"></i>
          <span class="menu-title">Subscription plans</span>
          <!-- <i class="menu-arrow"></i> -->
        </a>
        
      </li>

      <li class="nav-item">
        <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
          <i class="fas fa-home menu-icon"></i>
         
          <span class="menu-title">Home</span>
          <i class="menu-arrow"></i>

        </a>
        <div class="collapse" id="ui-basic">
          <ul class="nav flex-column sub-menu">
            <li class="nav-item"> <a class="nav-link" href="{% url 'official:stories' %}">Success Stories</a></li>
            <li class="nav-item"> <a class="nav-link" href="{% url 'official:testimonial' %}">Testimonial</a></li>
            
          </ul>
        </div>
      </li>


      
    </ul>
  </nav>