keralazawaj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("web.urls", namespace="web")),
        path("api/user/", include("user.urls", namespace="user")),
        path("api-auth/", include("rest_framework.urls")),
        path("official/", include("official.urls", namespace="official")),
        path("official/api/", include("officialapi.urls", namespace="officialapi")),
        path("tinymce/", include("tinymce.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

admin.site.site_header = "Keralazawaj Administration"
admin.site.site_title = "Keralazawaj Admin Portal"
admin.site.index_title = "Welcome to Keralazawaj Admin Portal"

web/urls.py
from . import views
from django.urls import path


app_name = "web"

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login, name="login"),
    path("register/<int:registerid>", views.register, name="register"),
    path("pic-upload/", views.profile_picupload, name="profile_picupload"),
    path("edit-profilepic/<str:id>/", views.edit_profilepic, name="edit_profilepic"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("like/", views.like, name="like"),
    path("like-premium/", views.likes_premium, name="likes_premium"),
    path("matches/", views.matches, name="matches"),
    path("matches-premium/", views.matches_premium, name="matches_premium"),
    path("view-profile/<str:pk>/", views.view_profile, name="view_profile"),
    path("view-profile-premium", views.view_profile_premium, name="view_profile_premium"),
    path("user-profile/", views.user_profile, name="user_profile"),
    path("contact/", views.contact, name="contact"),
    path("privacy/", views.privacy, name="privacy"),
    path("terms&condition/", views.terms, name="terms"),
    path("password_reset/", views.password_reset, name="password_reset"),
    path("chat/", views.chat, name="chat"),
    path("user-ajax", views.user_ajax, name="user_ajax"),
    path("chat-two/", views.chattwo, name="chat_two"),
    path("chat-direct/", views.chat_direct, name="chat_direct"),
    path("change_password/<str:email>/", views.change_password, name="change_password"),
    # --------------
    path("subscription-plans-view/", views.subscription_plans_view, name="subscription_plans_view"),
    path("payment-view/", views.payment_view, name="payment_view"),
]

templates/web/like.html
{% extends 'web/base-two.html' %}
{% load static %}
{% block content %}

    <main>
        <div class="like-premium-box p-4">
            <div class="">
              <img src="{% static 'web/images/icons/pre icon.png' %}" alt="missing" class="mx-auto d-block pre-icon">
            </div>
            <p class="pre-titile text-center">See all people who likes you with  <br>
              <span class="bismi-title-lk bismi-color">Kerala Zawaj</span> <br> 
              Premium
            </p>
            <div class="text-center p-4">
              <a href="{% url 'web:likes_premium' %}" id="prmum-btn" class="btn pre-button">See who likes you</a>
            </div>
        </div>

        <section class="profile-blur-section view-section-mt">
            <div class="container py-5">
                <div class="row">
                    <div class="col-12">
                        <div class="text-center">
                            <h2>Profiles likes you</h2>
                        </div>
                    </div>
                </div>
            </div>
  
            <div class="container like-box">
                <div class="row">
                    <div class="col-lg-4 col-md-6 col-sm-6 col-6 like-box-col">
                      <div class="card like-box-card p-3">
                          <img class="card-img-top d-block mx-auto blur-img" src="{% static 'web/images/profiles/blur-img.png' %}" alt="Card image cap">
                          <div class="card-body text-center">
                            <h5 class="card-title">Jasmin</h5>
                            <p class="card-text">Lorem ipsum elit.</p>
                            
                          </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-6 col-6 like-box-col">
                      <div class="card like-box-card p-3">
                          <img class="card-img-top d-block mx-auto blur-img" src="{% static 'web/images/profiles/blur-img.png' %}" alt="Card image cap">
                          <div class="card-body text-center">
                              <h5 class="card-title">Jasmin</h5>
                              <p class="card-text">Lorem ipsum elit.</p>
                              
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-6 col-6 like-box-col">
                      <div class="card like-box-card p-3">
                          <img class="card-img-top d-block mx-auto blur-img" src="{% static 'web/images/profiles/blur-img.png' %}" alt="Card image cap">
                          <div class="card-body text-center">
                              <h5 class="card-title">Jasmin</h5>
                              <p class="card-text">Lorem ipsum elit.</p>
                              
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-6 col-6 like-box-col">
                      <div class="card like-box-card p-3">
                          <img class="card-img-top d-block mx-auto blur-img" src="{% static 'web/images/profiles/blur-img.png' %}" alt="Card image cap">
                          <div class="card-body text-center">
                              <h5 class="card-title">Jasmin</h5>
                              <p class="card-text">Lorem ipsum elit.</p>
                              
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-6 col-6  like-box-col">
                      <div class="card like-box-card p-3">
                          <img class="card-img-top d-block mx-auto blur-img" src="{% static 'web/images/profiles/blur-img.png' %}" alt="Card image cap">
                          <div class="card-body text-center">
                              <h5 class="card-title disabled">Jasmin</h5>
                              <p class="card-text">Lorem ipsum elit.</p>
                              
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-6 col-6  like-box-col">
                      <div class="card like-box-card p-3">
                          <img class="card-img-top d-block mx-auto blur-img" src="{% static 'web/images/profiles/blur-img.png' %}" alt="Card image cap">
                          <div class="card-body text-center">
                              <h5 class="card-title">Jasmin</h5>
                              <p class="card-text">Lorem ipsum elit.</p>
                              
                            </div>
                        </div>
                    </div>
                   
                </div>
            </div>
        </section>
        
        <section class="area-seven position-relative">
          <div class="container">
            <div class="row">
              <div class="col-lg-2 col-md-4 col-sm-4 col-4 d-flex align-items-center">
                <div class="download-logo-second card ">
                  <a href=""><img src="{% static 'web/images/icons/playstore-logo.png' %}" alt="" class="apple-android mx-auto d-block"></a>
                </div>
              </div>
      
              <div class="col-lg-2 col-md-4 col-sm-4 col-4 d-flex align-items-center">
                <div class="download-logo-second card">
                <a href="">  <img src="{% static 'web/images/icons/apple_store-removebg-preview.png' %}" alt="" class="apple-android mx-auto d-block"></a>
                </div>
              </div>
      
              <div class="col-lg-5 col-md-4 col-sm-4 d-md-none d-sm-none d-lg-block d-none col-4">
                <div class="download-content">
                  <p class="dan">Download the app now!</p>
      
                </div>
              </div>
              <div class="col-lg-3 col-md-4 col-sm-4 col-4">
                <div class="">
                  <img src="{% static 'web/images/icons/phone-logo.png' %}" alt="" class="mobile-logo position-absolute" style="bottom: 0;">
                </div>
              </div>
            </div>
          </div>
      
        </section>
    </main>

    {% include 'web/partials/footer.html' %}
   

{% endblock %}
{% block javascript %}
<script src="{% static 'web/js/login-check.js' %}"></script>
<script src="{% static 'web/js/helper.js' %}"></script>
{% endblock %}

templates/web/matches.html
{% extends 'web/base-two.html' %}
{% load static %}
{% block content %}
  

    <main>
        <div class="like-premium-box p-4">
            <div class="">
              <img src="{% static 'web/images/icons/pre matches.png' %}" alt="missing" class="mx-auto d-block pre-icon">
            </div>
            <p class="pre-titile text-center">
                You have great matches,<br>see all matches with <br>
              <span class="bismi-title-lk bismi-color">Kerala Zawaj</span> <br> 
              Premium
            </p>
            <div class="text-center p-4">
            <a href="{% url 'web:matches_premium' %}"> <button class="btn pre-button">See all matches</button> </a> 
    
            </div>
        </div>
    
        <section class="profile-blur-section view-section-mt"> 
              <div class="container py-5">
                  <div class="row">
                      <div class="col-12">
                          <div class="text-center">
                              <h2>Profiles with Matches</h2>
                          </div>
                      </div>
                  </div>
              </div>
    
              <div class="container like-box">
                  <div class="row">
                      <div class="col-lg-4 col-md-6 col-sm-6 col-6 like-box-col">
                        <div class="card like-box-card p-3">
                            <img class="card-img-top d-block mx-auto blur-img" src="{% static 'web/images/profiles/blur-img.png' %}" alt="Card image cap">
                            <div class="card-body text-center">
                              <h5 class="card-title">Jasmin</h5>
                              <p class="card-text">Lorem ipsum elit.</p>
                              
                            </div>
                          </div>
                      </div>
                      <div class="col-lg-4 col-md-6 col-sm-6 col-6 like-box-col">
                        <div class="card like-box-card p-3">
                            <img class="card-img-top d-block mx-auto blur-img" src="{% static 'web/images/profiles/blur-img.png' %}" alt="Card image cap">
                            <div class="card-body text-center">
                                <h5 class="card-title">Jasmin</h5>
                                <p class="card-text">Lorem ipsum elit.</p>
                                
                              </div>
                          </div>
                      </div>
                      <div class="col-lg-4 col-md-6 col-sm-6 col-6 like-box-col">
                        <div class="card like-box-card p-3">
                            <img class="card-img-top d-block mx-auto blur-img" src="{% static 'web/images/profiles/blur-img.png' %}" alt="Card image cap">
                            <div class="card-body text-center">
                                <h5 class="card-title">Jasmin</h5>
                                <p class="card-text">Lorem ipsum elit.</p>
                                
                              </div>
                          </div>
                      </div>
                      <div class="col-lg-4 col-md-6 col-sm-6 col-6 like-box-col">
                        <div class="card like-box-card p-3">
                            <img class="card-img-top d-block mx-auto blur-img" src="{% static 'web/images/profiles/blur-img.png' %}" alt="Card image cap">
                            <div class="card-body text-center">
                                <h5 class="card-title">Jasmin</h5>
                                <p class="card-text">Lorem ipsum elit.</p>
                                
                              </div>
                          </div>
                      </div>
                      <div class="col-lg-4 col-md-6 col-sm-6 col-6 like-box-col">
                        <div class="card like-box-card p-3">
                            <img class="card-img-top d-block mx-auto blur-img" src="{% static 'web/images/profiles/blur-img.png' %}" alt="Card image cap">
                            <div class="card-body text-center">
                                <h5 class="card-title disabled">Jasmin</h5>
                                <p class="card-text">Lorem ipsum elit.</p>
                                
                              </div>
                          </div>
                      </div>
                      <div class="col-lg-4 col-md-6 col-sm-6 col-6 like-box-col">
                        <div class="card like-box-card p-3">
                            <img class="card-img-top d-block mx-auto blur-img" src="{% static 'web/images/profiles/blur-img.png' %}" alt="Card image cap">
                            <div class="card-body text-center">
                                <h5 class="card-title">Jasmin</h5>
                                <p class="card-text">Lorem ipsum elit.</p>
                                
                              </div>
                          </div>
                      </div>
                     
                  </div>
              </div>
        </section>

        <section class="area-seven position-relative">
          <div class="container">
            <div class="row">
              <div class="col-lg-2 col-md-4 col-sm-4 col-4 d-flex align-items-center">
                <div class="download-logo-second card ">
                 <a href=""> <img src="{% static 'web/images/icons/playstore-logo.png' %}" alt="" class="apple-android mx-auto d-block"> </a>
                </div>
              </div>
      
              <div class="col-lg-2 col-md-4 col-sm-4 col-4 d-flex align-items-center">
                <div class="download-logo-second card">
                <a href=""><img src="{% static 'web/images/icons/apple_store-removebg-preview.png' %}" alt="" class="apple-android mx-auto d-block"></a>
                </div>
              </div>
      
              <div class="col-lg-5 col-md-4 col-sm-4 d-md-none d-sm-none d-lg-block d-none col-4">
                <div class="download-content">
                  <p class="dan">Download the app now!</p>
      
                </div>
              </div>
              <div class="col-lg-3 col-md-4 col-sm-4 col-4">
                <div class="">
                  <img src="{% static 'web/images/icons/phone-logo.png' %}" alt="" class="mobile-logo position-absolute" style="bottom: 0;">
                </div>
              </div>
            </div>
          </div>
      
        </section>

    </main>

    {% include 'web/partials/footer.html' %}

 {% endblock %}
 {% block javascript %}
<script src="{% static 'web/js/login-check.js' %}"></script>
{% endblock %}

templates/web/privacy.html
{% extends 'web/base.html' %} {% load static %} {% block title %}Kerala Zawaj -
Home {% endblock %} {% block content %}

<header>
  <nav class="navbar navbar-expand-sm fixed-top main-nav main-nav-bg">
    <!-- Brand/logo -->
    <a class="navbar-brand" href="/">
      <img
        src="{% static 'web/images/KeralZawaj.svg' %}"
        alt="logo"
        class="bismi-logo"
      />
    </a>

    <!-- Links -->
    <ul class="navbar-nav">
      <li class="nav-item d-md-flex d-sm-none d-none">
        <a class="nav-link pr-4" href="#">Already a member ?</a>
      </li>
      <li class="nav-item">
        <a class="nav-link sign-in-btn" href="{% url 'web:login' %}">Sign In</a>
      </li>
    </ul>
  </nav>
</header>

<main class="">
  <section style="margin-top: 6rem" class="pb-5 pt-5">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <h3>Privacy Policy</h3>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-12">
          <p class="prvc-terms">Gedexo built the Keralazawaj app as a Free app. This SERVICE is provided by Gedexo at no cost and is intended for use as is.</p>
          <p class="prvc-terms">
            This page is used to inform visitors regarding our policies with the
            collection, use, and disclosure of Personal Information if anyone
            decided to use our Service.
          </p>
          <p class="prvc-terms">
            If you choose to use our Service, then you agree to the collection
            and use of information in relation to this policy. The Personal
            Information that we collect is used for providing and improving the
            Service. We will not use or share your information with anyone
            except as described in this Privacy Policy.
          </p>
          <p class="prvc-terms">
            The terms used in this Privacy Policy have the same meanings as in
            our Terms and Conditions, which are accessible at Keralazawaj unless
            otherwise defined in this Privacy Policy.
          </p>
          <p class="prvc-terms">
            <strong>Information Collection and Use</strong>
          </p>
          <p>
            For a better experience, while using our Service, we may require you
            to provide us with certain personally identifiable information. The
            information that we request will be retained by us and used as
            described in this privacy policy.
          </p>
          <div>
            <p class="prvc-terms">
              The app does use third-party services that may collect information
              used to identify you.
            </p>
            <p class="prvc-terms">
              Link to the privacy policy of third-party service providers used
              by the app
            </p>
            
            <ul>
              <li><a href="https://www.google.com/policies/privacy/" target="_blank" rel="noopener noreferrer">Google Play Services</a></li>
            </ul>
          </div>
          <p><strong>Log Data</strong></p>
          <p class="prvc-terms">
            We want to inform you that whenever you use our Service, in a case
            of an error in the app we collect data and information (through
            third-party products) on your phone called Log Data. This Log Data
            may include information such as your device Internet Protocol (“IP”)
            address, device name, operating system version, the configuration of
            the app when utilizing our Service, the time and date of your use of
            the Service, and other statistics.
          </p>
          <p class="prvc-terms"><strong>Cookies</strong></p>
          <p>
            Cookies are files with a small amount of data that are commonly used
            as anonymous unique identifiers. These are sent to your browser from
            the websites that you visit and are stored on your device's internal
            memory.
          </p>
          <p class="prvc-terms">
            This Service does not use these “cookies” explicitly. However, the
            app may use third-party code and libraries that use “cookies” to
            collect information and improve their services. You have the option
            to either accept or refuse these cookies and know when a cookie is
            being sent to your device. If you choose to refuse our cookies, you
            may not be able to use some portions of this Service.
          </p>
          <p><strong>Service Providers</strong></p>
          <p class="prvc-terms">
            We may employ third-party companies and individuals due to the
            following reasons:
          </p>
          <ul>
            <li>To facilitate our Service;</li>
            <li>To provide the Service on our behalf;</li>
            <li>To perform Service-related services; or</li>
            <li>To assist us in analyzing how our Service is used.</li>
          </ul>
          <p class="prvc-terms">
            We want to inform users of this Service that these third parties
            have access to their Personal Information. The reason is to perform
            the tasks assigned to them on our behalf. However, they are
            obligated not to disclose or use the information for any other
            purpose.
          </p>
          <p><strong>Security</strong></p>
          <p class="prvc-terms">
            We value your trust in providing us your Personal Information, thus
            we are striving to use commercially acceptable means of protecting
            it. But remember that no method of transmission over the internet,
            or method of electronic storage is 100% secure and reliable, and we
            cannot guarantee its absolute security.
          </p>
          <p><strong>Links to Other Sites</strong></p>
          <p class="prvc-terms">
            This Service may contain links to other sites. If you click on a
            third-party link, you will be directed to that site. Note that these
            external sites are not operated by us. Therefore, we strongly advise
            you to review the Privacy Policy of these websites. We have no
            control over and assume no responsibility for the content, privacy
            policies, or practices of any third-party sites or services.
          </p>
          <p><strong>Children’s Privacy</strong></p>
          <div>
            <p class="prvc-terms">
              These Services do not address anyone under the age of 13. We do
              not knowingly collect personally identifiable information from
              children under 13 years of age. In the case we discover that a
              child under 13 has provided us with personal information, we
              immediately delete this from our servers. If you are a parent or
              guardian and you are aware that your child has provided us with
              personal information, please contact us so that we will be able to
              do the necessary actions.
            </p>
          </div>
          <!---->
          <p><strong>Changes to This Privacy Policy</strong></p>
          <p class="prvc-terms">
            We may update our Privacy Policy from time to time. Thus, you are
            advised to review this page periodically for any changes. We will
            notify you of any changes by posting the new Privacy Policy on this
            page.
          </p>
          <p class="prvc-terms">This policy is effective as of 2021-12-28</p>
          
          <!-- <p class="prvc-terms">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum alias, nobis deserunt perferendis repellendus molestias optio, beatae, quasi cupiditate et id accusamus dolorem in voluptate doloremque. Pariatur veniam ad dignissimos.
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet perspiciatis saepe natus, tenetur tempora minus eos earum enim suscipit explicabo praesentium, ipsa ab laudantium inventore numquam nulla doloribus dolor quidem.
                        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellat fugit esse, suscipit ea atque ad voluptatem aliquid eum itaque? Consequuntur tempora enim maxime cum dignissimos suscipit odit nulla assumenda sit!
                    </p> -->
        </div>
      </div>
    </div>
  </section>

  <section class="area-seven position-relative">
    <div class="container">
      <div class="row">
        <div class="col-lg-2 col-md-4 col-sm-4 col-4">
          <div class="download-logo-second card pb-4">
          <a href="">  <img
              src="{% static 'web/images/icons/playstore-logo.png' %}"
              alt=""
              class="apple-android mx-auto d-block"
            /></a>
          </div>
        </div>

        <div class="col-lg-2 col-md-4 col-sm-4 col-4">
          <div class="download-logo-second card pb-4">
            <a href=""><img
              src="{% static 'web/images/icons/apple store.png' %}"
              alt=""
              class="apple-android mx-auto d-block"
            /></a>
          </div>
        </div>

        <div
          class="
            col-lg-5 col-md-4 col-sm-4
            d-md-none d-sm-none d-lg-block d-none
            col-4
          "
        >
          <div class="download-content">
            <p class="dan">Download the app now!</p>
          </div>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-4 col-4">
          <div class="">
            <a href=""><img
              src="{% static 'web/images/icons/phone-logo.png' %}"
              alt=""
              class="mobile-logo position-absolute"
              style="bottom: 0"
            /></a>
          </div>
        </div>
      </div>
    </div>
  </section>

</main>

{% endblock %}

templates/web/terms.html
{% extends 'web/base.html' %}
{% load static %}
{% block title %}Kerala Zawaj - Home {% endblock %}
{% block content %}

<header>
    <nav class="navbar navbar-expand-sm fixed-top main-nav main-nav-bg">
      <!-- Brand/logo -->
      <a class="navbar-brand " href="/">
        <img src="{% static 'web/images/KeralZawaj.svg' %}" alt="logo" class="bismi-logo">
      </a>
  
      <!-- Links -->
      <ul class="navbar-nav">
        <li class="nav-item d-md-flex d-sm-none d-none">
          <a class="nav-link pr-4" href="#">Already a member ?</a>
        </li>
        <li class="nav-item">
          <a class="nav-link sign-in-btn" href="{% url 'web:login' %}">Sign In</a>
        </li>
      </ul>
    </nav>
  </header>

  <main class="">
      <section style="margin-top: 6rem;" class="pb-5 pt-5">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h3>Terms & Conditions</h3>

                </div>
                <div class="col-12">
                    <p class="prvc-terms">Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem delectus provident voluptas, illum alias dolor in natus possimus repudiandae, magni similique aliquid. Illo, ipsa dicta excepturi voluptates quibusdam iure quia
                        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Recusandae consequatur ipsum obcaecati impedit reprehenderit ratione quo, delectus accusantium labore. Natus, doloribus facilis! Omnis molestiae architecto laborum provident nostrum praesentium quis?
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum alias, nobis deserunt perferendis repellendus molestias optio, beatae, quasi cupiditate et id accusamus dolorem in voluptate doloremque. Pariatur veniam ad dignissimos.
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet perspiciatis saepe natus, tenetur tempora minus eos earum enim suscipit explicabo praesentium, ipsa ab laudantium inventore numquam nulla doloribus dolor quidem.
                        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellat fugit esse, suscipit ea atque ad voluptatem aliquid eum itaque? Consequuntur tempora enim maxime cum dignissimos suscipit odit nulla assumenda sit!
                    </p>
                    <p class="prvc-terms">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum alias, nobis deserunt perferendis repellendus molestias optio, beatae, quasi cupiditate et id accusamus dolorem in voluptate doloremque. Pariatur veniam ad dignissimos.
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet perspiciatis saepe natus, tenetur tempora minus eos earum enim suscipit explicabo praesentium, ipsa ab laudantium inventore numquam nulla doloribus dolor quidem.
                        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellat fugit esse, suscipit ea atque ad voluptatem aliquid eum itaque? Consequuntur tempora enim maxime cum dignissimos suscipit odit nulla assumenda sit!
                    </p>

                </div>
            </div>
        </div>

      </section>

      <section class="area-seven position-relative">
        <div class="container">
          <div class="row">
            <div class="col-lg-2 col-md-4 col-sm-4 col-4 d-flex align-items-center">
              <div class="download-logo-second card ">
               <a href=""> <img src="{% static 'web/images/icons/playstore-logo.png' %}" alt="" class="apple-android mx-auto d-block"></a>
              </div>
            </div>
    
            <div class="col-lg-2 col-md-4 col-sm-4 col-4 d-flex align-items-center">
              <div class="download-logo-second card">
              <a href="">  <img src="{% static 'web/images/icons/apple_store-removebg-preview.png' %}" alt="" class="apple-android mx-auto d-block"></a>
              </div>
            </div>
    
            <div class="col-lg-5 col-md-4 col-sm-4 d-md-none d-sm-none d-lg-block d-none col-4">
              <div class="download-content">
                <p class="dan">Download the app now!</p>
    
              </div>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-4 col-4">
              <div class="">
                <img src="{% static 'web/images/icons/phone-logo.png' %}" alt="" class="mobile-logo position-absolute" style="bottom: 0;">
              </div>
            </div>
          </div>
        </div>
    
      </section>
  </main>

{% endblock %}