keralazawaj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("web.urls", namespace="web")),
        path("api/user/", include("user.urls", namespace="user")),
        path("api-auth/", include("rest_framework.urls")),
        path("official/", include("official.urls", namespace="official")),
        path("official/api/", include("officialapi.urls", namespace="officialapi")),
        path("tinymce/", include("tinymce.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

admin.site.site_header = "Keralazawaj Administration"
admin.site.site_title = "Keralazawaj Admin Portal"
admin.site.index_title = "Welcome to Keralazawaj Admin Portal"

web/urls.py
from . import views
from django.urls import path


app_name = "web"

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login, name="login"),
    path("register/<int:registerid>", views.register, name="register"),
    path("pic-upload/", views.profile_picupload, name="profile_picupload"),
    path("edit-profilepic/<str:id>/", views.edit_profilepic, name="edit_profilepic"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("like/", views.like, name="like"),
    path("like-premium/", views.likes_premium, name="likes_premium"),
    path("matches/", views.matches, name="matches"),
    path("matches-premium/", views.matches_premium, name="matches_premium"),
    path("view-profile/<str:pk>/", views.view_profile, name="view_profile"),
    path("view-profile-premium", views.view_profile_premium, name="view_profile_premium"),
    path("user-profile/", views.user_profile, name="user_profile"),
    path("contact/", views.contact, name="contact"),
    path("privacy/", views.privacy, name="privacy"),
    path("terms&condition/", views.terms, name="terms"),
    path("password_reset/", views.password_reset, name="password_reset"),
    path("chat/", views.chat, name="chat"),
    path("user-ajax", views.user_ajax, name="user_ajax"),
    path("chat-two/", views.chattwo, name="chat_two"),
    path("chat-direct/", views.chat_direct, name="chat_direct"),
    path("change_password/<str:email>/", views.change_password, name="change_password"),
    # --------------
    path("subscription-plans-view/", views.subscription_plans_view, name="subscription_plans_view"),
    path("payment-view/", views.payment_view, name="payment_view"),
]

templates/web/partials/footer.html
{% load static %}
<footer class="footer">
    <div class="container">
      <div class="row ">

        <div class="cl-lg-12 col-md-12 col-sm-12 col-12">
          <ul class="privacy d-lg-flex d-md-none d-sm-none d-none">
            <li><a href="{% url 'web:contact' %}">Contact Us</a> <span class=""> | </span> </li>
            <li><a href="{% url 'web:terms' %}">Terms & Conditions</a> <span class=""> |</span> </li>
            <li><a href="{% url 'web:privacy' %}"> Privacy Policy</a></li>
          </ul>

          <ul class="text-center mob-ft-privacy d-lg-none d-md-block d-sm-block d-block">
            <li><a href="{% url 'web:contact' %}">Contact Us</a> </li>
            <li><a href="{% url 'web:terms' %}">Terms & Conditions</a> </li>
            <li><a href="{% url 'web:privacy' %}"> Privacy Policy</a></li>
          </ul>
        </div>

        <div class="col-lg-12 col-md-6 col-sm-6 col-6">
          <div class="footer-logo">
            <!-- <h2 class="footer-logo">LOGO</h2> -->
            <a class="navbar-brand " href="/">
              <img src="{% static 'web/images/KeralZawaj.svg' %}" alt="logo" class="bismi-logo">
            </a>
            <ul style="list-style: none;">
              <li class="footer-mob-number-li">
                <i class="fas fa-phone-alt pr-1"></i>
                <a href="">9876543210</a>
              </li>
            </ul>
          </div>
        </div>

        <div class="col-lg-12 col-md-6 col-sm-6 col-6">
          <div class="social d-lg-flex  d-md-block d-sm-block d-block">
            <span class="follow-us-tt">Follow us on</span>
            <ul>
              <li class="social-icon"><a href=""><i class="fab fa-facebook"></i></a></li>
              <li class="social-icon"><a href=""><i class="fab fa-instagram"></i></a></li>
              <li class="social-icon"><a href=""><i class="fab fa-twitter"></i></a></li>
            </ul>
          </div>
        </div>
        <div class="col-12 text-center">
          <p class="copyright"> Copyright © 2021. All rights reserved.Passionately created by <a
              href="https://gedexo.com/" target="_blank">Gedexo</a> Designs</p>
        </div>
      </div>

    </div>
  </footer>

templates/web/partials/header.html
{% load static %}
<header>
    <nav class="navbar navbar-expand-sm fixed-top main-nav main-nav-bg dash-nav" id="nav">
        <!-- Brand/logo -->
        <a class="navbar-brand" href="{% url 'web:dashboard' %}">
            <img src="{% static 'web/images/kerala zawaj logo.svg' %}" alt="miss" class="logo-dashboard" style="width: 43px;">
        </a>

        <div class="form-group has-search mob-nav-title-hide d-lg-flex d-md-none d-sm-none d-none dash-search-box">
            <span class="fa fa-search form-control-feedback"></span>
            <input type="text" class="form-control" placeholder="Search">
        </div>

        <ul class="navbar-nav mt-lg-0 bismi-nav">
            <li class="nav-item  bismi-nav-link mob-nav-link-res bismi-nav-li">
                
                <a class="nav-link" href="{% url 'web:dashboard' %}" id="nav1">
                    <span class="mob-nav-title-hide">Discover </span>
                    <i>
                        <img src="{% static 'web/images/icons/nav-icons/discovery.svg' %}" alt=""
                            class="img-dashboard-icon">
                    </i>
                </a>
            </li>
            <li class="nav-item bismi-nav-link mob-nav-link-res bismi-nav-li" id="premieumsubscrptn">
                <a class="nav-link prm-chk likes" href="{% url 'web:subscription_plans_view' %}" id="nav2"> <span class="mob-nav-title-hide">Likes</span> 
                     <i class=""><img src="{% static 'web/images/icons/nav-icons/heart.png' %}" alt="" class="img-dashboard-icon"></i>
                     <i class="icon-bell mx-0" id="likeCountItag"><span class="count" id="likeCount"></span></i>
                    
                </a>

            </li>
            <li class="nav-item bismi-nav-link mob-nav-link-res bismi-nav-li" id="premieumsubscrptn">
                <a class="nav-link prm-chk matches" href="{% url 'web:subscription_plans_view' %}" id="nav3"><span class="mob-nav-title-hide">Matches</span>
                    <i><img src="{% static 'web/images/icons/nav-icons/matches.png' %}" alt=""class="img-dashboard-icon"></i>
                    <i class="icon-bell mx-0" id="matchCountItag"><span class="count" id="matchCount"></span></i>
                </a>
            </li>

            <li class="nav-item bismi-nav-link mob-nav-link-res bismi-nav-li" id="premieumsubscrptn">
                <a class="nav-link prm-chk chats" href="{% url 'web:subscription_plans_view' %}"><span class="mob-nav-title-hide">Messages</span>
                    <i class="fas fa-comment img-dashboard-icon-chat-nav"></i>   
                </a>
            </li>

        </ul>
        <div>

        </div>

        <!-- Links -->
        <ul class="navbar-nav mt-lg-0 mob-nav-ul-two">
            <!-- <li class="nav-item bismi-nav-link mob-nav-link-res-second mob-nav-title-hide bismi-nav-li-second">
                    
                    <a class="nav-link" href="{% url 'web:chat_direct' %}"><i class="fas fa-comment bismi-nav-li-second-icon chat-icondpadd"></i>
                    <i class="icon-bell mx-0" id="chatCountItag"><span class="count" id="ChatCount"></span></i>
                    </a>
            </li> -->
            <li class="nav-item bismi-nav-link mob-nav-link-res-second bismi-nav-li-second dropdown" id="mob-show-dropdown">

                <a class="nav-link dropdown"  id="nav4">

                    <span class="mob-nav-title-hide" id="userNameViewSapn"></span>
                    <img id="userImgViewId"  alt="" class="mob-nav-user bismi-nav-li-second-icon bismi-nav-li-second-icon-user userhedaer-image">
                </a>
                    <!-- <i class="fas fa-user-circle mob-nav-user bismi-nav-li-second-icon bismi-nav-li-second-icon-user"></i> -->
                    <ul class="dropdown-menu dropdown-menu-header">
                        <li id="btnMyProfile">
                            <a>My profile</a>
                        </li>
                        <li id="btnPartnerPreference">
                            <a>Partner Preferences</a>
                        </li>
                        <li id="btnLogout" class="" title="Logout">
                            <a style="color: #fff;"><span class="mob-nav-title-hide" id="userNameViewSapn"></span>Logout</a> 
                        </li>
                    </ul>
                
            </li>

                <!-- -----logout  -->
            <!-- <li class="nav-item bismi-nav-link mob-nav-link-res-second bismi-nav-li-second padd" title="Logout">
                <a class="nav-link" id="btnLogout"><span class="mob-nav-title-hide" id="userNameViewSapn"></span>
                    <i class="fas fa-power-off mob-nav-user bismi-nav-li-second-icon bismi-nav-li-second-icon-user"></i>
                </a>
                
            </li> -->
        </ul>
    </nav>
</header>
<!-- --------------phone navbar----------- -->
<div class="container-fluid" id="phoneMenu">
    <div class="row">
      <div class="col-12">
        <ul class="text-center">
          <li id="close-navId"><a class="float-right pb-2 pr-3 far fa-times"></a></li>
          <li id="btnMyProfile"><a>My Profile</a></li>
          <li id="btnPartnerPreference"><a >Partner Preference</a></li>
          <li id="btnLogout" ><a id="btnLogout" style="color: #fff !important;"></a> Logout</li>
          
        </ul>

      </div>
    </div>
  </div>
  
{% block javascript %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script>
    $.ajax({
        url: "https://keralazawaj.com/api/user/get_user/",
        type: "GET",
        beforeSend: function (xhr) {
            xhr.setRequestHeader(
                "Authorization",
                "Token " + localStorage.getItem("token")
            );
        },
        success: function (response) {
            $("#userNameViewSapn").html(response['name'])
            $("#userImgViewId").prop('src', response.image.image_one['medium_square_crop'])
        }
    });
</script>

<script>
    $("[id=btnLogout]").click(function () {
        $.ajax({
            url: "https://keralazawaj.com/api/user/logout/",
            type: "GET",
            beforeSend: function (xhr) {
                xhr.setRequestHeader(
                    "Authorization",
                    "Token " + localStorage.getItem("token")
                );
            },
            success: function () {
                localStorage.removeItem("token")
                window.location = "https://keralazawaj.com/"
            },
        });
    });
</script>

<script>
    $(document).ready(function(){
        $("#likeCountItag").hide();
        $("#matchCountItag").hide();
        $("#chatCountItag").hide();
        $.ajax({
            url: "https://keralazawaj.com/api/user/liked-count/",
            type: "GET",
            beforeSend: function (xhr) {
                xhr.setRequestHeader(
                    "Authorization",
                    "Token " + localStorage.getItem("token")
                );
            },
            success: function (response) {
                if(response['count'] > 0){
                    $("#likeCountItag").show();
                    $("#likeCount").html(response['count']);
                }
                if(response['matched_count'] > 0){
                    $("#matchCountItag").show();
                    $("#matchCount").html(response['matched_count']);
                }
              
                
            },
        });
    })
</script>

<script>
    $('[id=btnMyProfile]').click(function(){
        
        window.location = '/user-profile/?lat=profile'
    });
</script>

<script>
    $('[id=btnPartnerPreference]').click(function(){
        
        window.location = '/user-profile/?lat=partner-preference'
    });
</script>
<script src="{% static 'web/js/mobile-navigation.js' %}"></script>



{% endblock %}